hashicorp/cdktf-aws-cdk

README.md
this commit also bumps the adapter version to 0.2 as we now depend on cdktf 0.8.0-pre.2. In fact 0.1.11 already dependeded on that version
=> feat!: update readme with latest version info

src/aws-adapter.ts
Returned undefined so when the value gets processed it's handled safely
Fixes #97
=> fix: fixes handling AWS No:Value references

.projen/tasks.json, examples/typescript-cron-lambda/main.test.ts, examples/typescript-cron-lambda/package.json, examples/typescript-cron-lambda/yarn.lock, examples/typescript-manual-mapping/package.json, examples/typescript-manual-mapping/yarn.lock, examples/typescript-step-functions-mixed/cdktf-plus/README.md, examples/typescript-step-functions-mixed/cdktf-plus/aws-iam.ts, examples/typescript-step-functions-mixed/cdktf-plus/aws-lambda-function.ts, examples/typescript-step-functions-mixed/cdktf-plus/nodejs-function.ts, examples/typescript-step-functions-mixed/dist/fn-generate-id.js.map, examples/typescript-step-functions-mixed/dist/fn-reverse-id.js.map, examples/typescript-step-functions-mixed/main.test.ts, examples/typescript-step-functions-mixed/main.ts, examples/typescript-step-functions-mixed/package.json, examples/typescript-step-functions-mixed/yarn.lock, examples/typescript-step-functions/main.test.ts, examples/typescript-step-functions/package.json, examples/typescript-step-functions/yarn.lock, package.json, projen/index.ts, src/mapping/EventualConsistencyWorkaroundAspect.ts, src/tests/aws-lambda-function.test.ts
In a multi-stack scenario, only 1 `TimeProvider` is created across all stacks. This causes `cdktf synth` to fail with this error: `Found resources without a matching provider construct. Please make sure to add provider constructs [e.g. new RandomProvider(...)] to your stack for the following providers: time` when it gets to the second stack that creates sleep resources.
With this change CDK now creates one `TimeProvider` per stack.
=> fix: TimeProvider should be created for each unique stack

src/aws-adapter.ts, src/tests/aws-adapter.test.ts
Related to #84 #91
Uses https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/partition#dns_suffix to map the `AWS::URLSuffix` pseudo parameter ref.
See https://github.com/hashicorp/cdktf-aws-cdk/issues/84#issuecomment-1144556604
FYI: haven't tested this for real so far
=> feat: add mapping for URL Suffix pseudo parameter reference

.github/workflows/build.yml, .github/workflows/provider-upgrade.yml, .github/workflows/release.yml, .github/workflows/stale.yml, .github/workflows/upgrade-main.yml, .projenrc.ts, projen/index.ts
Was auditing the repo today and noticed that `actions/download-artifact` was missing, and `actions/stale` has a newer version we can use. We can also update `setup-copywrite` to the newer version that no longer needs a token to be passed as an input.
=> chore: pin additional GitHub Actions versions

.copywrite.hcl, .github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/cloudcontrol-mapping.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/workflows/stale.yml, .projen/jest-snapshot-resolver.js, projen/index.ts
Copied from hashicorp/terraform-cdk-action#50: I looked into whether there is a Projen-native way to generate issue templates and there's not (there only is for the pull request template), and translating our existing YAML templates into JavaScript so that Projen can compile it back into YAML seems silly. So, just adding in the YAML files and having them not be managed by Projen at all seemed like the best solution. IMO this also makes them easier to maintain in the future (for example, if we want to add a new field to an issue template in all our repos).
=> chore: add issue templates

.github/dependabot.yml, .github/workflows/automerge.yml, .github/workflows/upgrade-main.yml, .projen/jest-snapshot-resolver.js, projen/auto-merge.ts, projen/index.ts
Some productivity enhancements around dependency updates.
Note that I know that Projen can manage Dependabot configs, however as far as I could tell from the (limited) docs, it doesn't support creating a Dependabot config like this with multiple subdirectories. So, I figured the manual route is just the easiest way to go.
=> chore: improve dependency updates

.github/workflows/auto-approve.yml, .github/workflows/provider-upgrade.yml, .github/workflows/upgrade-main.yml, projen/auto-approve.ts, projen/index.ts, projen/provider-upgrade.ts
Fixes a few build-related issues:
- removes the `synchronize` trigger from the auto-approve workflow because it's obnoxious (re-approving the PR on every update)
- attempts to fix the `upgrade-main` workflow because it's still not working -- hopefully adding the `chown` does the trick
- attempts to get the `provider-upgrade` workflow working which also hasn't run in months due to a missing token
=> chore: fix various build issues

examples/typescript-cron-lambda/package-lock.json, examples/typescript-cron-lambda/yarn.lock, examples/typescript-manual-mapping/package-lock.json, examples/typescript-manual-mapping/yarn.lock, examples/typescript-step-functions-mixed/package-lock.json, examples/typescript-step-functions-mixed/package.json, examples/typescript-step-functions-mixed/yarn.lock, examples/typescript-step-functions/package-lock.json, examples/typescript-step-functions/package.json, examples/typescript-step-functions/yarn.lock
Rather than waiting for Dependabot to fix each and every dependency individually, I figured I'd go through and `npm audit fix` them all in one fell swoop.
=> chore(deps): upgrade examples for security

.github/workflows/build.yml, projen/index.ts
#211 finally fixed the `provider-upgrade` workflow that hadn't been working in months, but now a new problem appears: as you can see from #233, we're now getting PRs that wind up empty after the self-mutation step.
One option is to look into having the copyright header generation happen elsewhere in the process rather than in the build workflow, so that Projen correctly identifies that there aren't any changes. Long-term that might be the best solution but personally I don't have any ideas how to make that happen (in particular without forcing users to have HashiCorp's copywrite installed in order to run Projen).
In the short term, the best option is to add some steps to the build workflow to check whether all of the changes were undone after Projen's self-mutation, and to close the PR if …
=> chore: auto-close PRs with no changes

examples/typescript-cron-lambda/package.json, examples/typescript-manual-mapping/package.json, examples/typescript-step-functions-mixed/package.json, examples/typescript-step-functions/package.json
This will allow the Jest upgrade PRs (#389, #390, #394, #395) to pass.
=> chore: update snapshots in example tests

examples/typescript-cron-lambda/tsconfig.json, examples/typescript-manual-mapping/tsconfig.json, examples/typescript-step-functions-mixed/tsconfig.json, examples/typescript-step-functions/tsconfig.json
This is a requirement to upgrade TypeScript to v5+
=> chore: remove charset from tsconfig files

.projen/deps.json, .projen/tasks.json, package.json, projenrc/index.ts, yarn.lock
This will allow them to be auto-updated in the future.
=> chore: remove hard-coded versions of jsii-docgen and rosetta

.github/workflows/auto-approve.yml, .github/workflows/automerge.yml, .github/workflows/build.yml, .github/workflows/provider-upgrade.yml, .github/workflows/release.yml, .github/workflows/update-snapshots.yml, .github/workflows/upgrade-cdktf.yml, .github/workflows/upgrade-main.yml, .github/workflows/upgrade-node.yml, .projenrc.ts, projenrc/auto-approve.ts, projenrc/index.ts
This also adds the ability for the github-actions bot user to approve PRs, now that that's enabled on this org.
=> chore(deps): update pinned versions of GitHub Actions

.github/workflows/auto-approve.yml, .github/workflows/automerge.yml, .github/workflows/upgrade-cdktf.yml, .github/workflows/upgrade-node.yml, projenrc/auto-approve.ts, projenrc/automerge.ts, projenrc/upgrade-cdktf.ts, projenrc/upgrade-node.ts
The auto-upgrade to Projen v0.85 broke a lot of our workflows overnight because of projen/projen#3762. This fixes it.
=> chore(ci): fix syntax for concurrency in workflows

.projen/deps.json, .projenrc.ts, package.json, yarn.lock
When resolving some other issues today, I noticed an end-of-life warning about JSII v5.2. We should upgrade it (and TypeScript) to v5.4.
=> chore(deps): upgrade jsii & typescript to v5.4

.github/workflows/build.yml, .github/workflows/release.yml, projenrc/index.ts
Something about [Projen v0.87](https://github.com/projen/projen/releases/tag/v0.87.0) caused our workflows to stop working with Dependabot. Specifically, the Checkout step on the self-mutation job is failing with `Error: Input required and not supplied: token`.
I think this is because Dependabot does not have access to secrets like `PROJEN_GITHUB_TOKEN`, so the solution is to use the built-in `GITHUB_TOKEN` and making sure that one has the appropriate permissions configured. I'm not 100% positive this will work, but there's no way to find out without merging this and trying it.
=> chore(ci): attempt to fix token permission issues

.github/workflows/release.yml, projenrc/index.ts
It just makes the release job slower than it needs to be, and if the tests passed during a build, then they should always pass during release anyway.
=> chore(ci): do not run integration tests during release

projenrc/cdktf-config.ts
v9 requires Node 18.18+ while our minNodeVersion is purposely set to 18.12. The easiest fix is to avoid upgrading eslint for now.
=> chore(deps): pin eslint to v8

examples/typescript-cron-lambda/package.json, examples/typescript-step-functions-mixed/main.test.ts, examples/typescript-step-functions-mixed/package.json, examples/typescript-step-functions/main.test.ts, examples/typescript-step-functions/package.json
For some reason, Dependabot was regularly updating this dependency for `typescript-manual-mapping`, but not for the other 3 examples. I think manually upgrading all of them to the latest will spur Dependabot back into action for the other 3 going forward.
This resolves some low-level security warnings.
=> chore(deps): upgrade aws-cdk-lib in examples

.projen/deps.json, package.json, projenrc/cdktf-config.ts, yarn.lock
There's a bunch of security alerts in this repo that can't/won't be fixed until CDKTF comes out with a 0.20.12 or even a 0.21.0 release. These all involve packages that are several layers deep (dependencies of dependencies of dependencies) to the point where it's quite possible this functionality really isn't used at all, but unfortunately the security scanners aren't smart enough to pick that up. The easiest (hacky but working) fix is to take advantage of Node's `packageResolutions` to hard-code these to the fixed versions. These overrides should be removed when we upgrade CDKTF.
=> chore(deps): address security vulnerabilities

scripts/check-jsii-versions.js
#989 forgot the script that's used to check for the latest supported version of JSII, oops!
=> chore(ci): add missing script that workflow depends on

.github/workflows/upgrade-cdktf.yml, .github/workflows/upgrade-jsii-typescript.yml, .github/workflows/upgrade-node.yml, projenrc/upgrade-cdktf.ts, projenrc/upgrade-jsii-typescript.ts, projenrc/upgrade-node.ts
This is very similar to cdktf/cdktf-provider-project#493. It turns out we were making these workflows a lot slower and more complicated than they needed to be by including the compilation and doc generation steps here, when we could just let the build workflow take care of that.
=> chore(ci): remove unnecessary compile step from workflow
